# Generated by Django 5.2.7 on 2025-10-28 19:14

import django.db.models.deletion
import notes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_pinned', '-updated_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Uploaded Image', 'verbose_name_plural': 'Uploaded Images'},
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, help_text='Note content in Markdown format'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When note was created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag (recycle bin)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Whether note is pinned to top of list'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Note title (required)', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When note was last modified'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(help_text='Note owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(help_text='Uploaded image file', upload_to=notes.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When image was uploaded'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(help_text='Image uploader', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'work', 'personal', 'ideas')", max_length=50)),
                ('color', models.CharField(default='#FFD580', help_text='Hex color code for tag chip', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When tag was created')),
                ('user', models.ForeignKey(help_text='Tag owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this note', related_name='notes', to='notes.tag'),
        ),
    ]
